version: '3'

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=account-service

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    links:
      - mysql:mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
    depends_on:
      - mysql

  account-service:
    build: ./account-service
    image: er/account-service:latest
    ports:
      - 8088:8080
    depends_on:
      - mysql

  location-service:
    build: ./location-service
    image: er/location-service:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  mysql-data: